# Generated by Django 5.2.7 on 2025-11-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('website_html_content', models.TextField()),
                ('website_plain_content', models.TextField()),
                ('url', models.URLField(unique=True)),
                ('publication_date', models.DateTimeField()),
            ],
        ),
    ]
