# Generated by Django 5.2.7 on 2025-11-03 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_scrapper', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Website_Content',
            new_name='WebsiteContent',
        ),
    ]
